---
avail_zone_comm: melbourne-qh2-uom
instance_image_comm: 215f9775-483c-4e0a-b703-d21a5c966f2e
instance_network_comm: qh2-uom-internal
instance_flavor_comm: uom.mse.2c9g

security_groups:
  name: COMP90024_Security
  description: "Security group for COMP90024"
  protocol: tcp
  remote_group: COMP90024_Security
  remote_ip_prefix: 0.0.0.0/0
  rules:
    - port_range_min: 22
      port_range_max: 22
    - port_range_min: 80
      port_range_max: 80
    - port_range_min: 8080
      port_range_max: 8080
    - port_range_min: 8000
      port_range_max: 8000
    - port_range_min: 443
      port_range_max: 443

keypair_name_comm: ccc_keypair
keypair_public_key_file_comm: ~/ccc_keypair.pem

volumes:
  - vol_name: first-vol
    vol_size: 61
  - vol_name: second-vol
    vol_size: 63
  - vol_name: third-vol
    vol_size: 63
  - vol_name: fourth-vol
    vol_size: 63

instances:
  - name: instance_1
  - name: instance_2
  - name: instance_3
  - name: instance_4
